title: Buttons
context:
    text: Command Button - Shadow
    button: Button Text
    text-sec: Input Button - Shadow
    text-origin: Command Button - No Shadow
    text-sec-origin: Input Button - No Shadow
    text-settings: Settings button
    text-location: Location button
    text-play: Play button
    text-pause: Pause button
    text-next: Next button
    text-prev: Previous button

status: inDevelopment
