title: Buttons
context:
    text: Command Button - Shadow
    button: Button Text
    text-sec: Input Button - Shadow
    text-origin: Command Button - No Shadow
    text-sec-origin: Input Button - No Shadow
